
input_file = "input.txt"
output_file = "gpm_map_mode_l_english.yml"

with open(input_file, "r") as file:
    lines = [line.rstrip() for line in file]

with open(output_file, "w") as file:
    
    file.write("### This file is generated by script and does not need any translation. ###\n")
    file.write("l_english:\n")
    # Write te main locs
    # GPM_MAP_MODE_RELIC_LIST
    template_string = "[THIS.gpm_{}_list]"
    file.write(" GPM_MAP_MODE_RELIC_LIST: \"§S")
    for line in lines:
        if line.startswith("#"):
            result = ""
        elif line.strip():
            result = template_string.format(line)
        else:
            result = ""

        file.write(result + "")
    file.write("§!\"\n")
    
    template_string = " {}_n: \"\\n${}$\""
    for line in lines:
        if line.startswith("#"):  # Check if the line is a comment
            result = line  # Keep the comment as-is
        elif line.strip():  # Check if the line is not empty
            # Replace all placeholders in the template string with the same value
            result = template_string.format(line, line)
        else:  # Keep empty lines as empty
            result = ""

        # Write the result to the output file
        file.write(result + "\n")


print(f"Results have been written to {output_file}")
