
input_file = "input.txt"
output_file = "gpm_tradable_relics_l_english.yml"

with open(input_file, "r") as file:
    lines = [line.rstrip() for line in file]

with open(output_file, "w", encoding="utf-8-sig") as file:
    file.write("### This file is generated by script and does not need any translation. ###\n")
    file.write("l_english:\n")
    
    template_string = " trade_action_{}: \"$gpm_relic_trade_prefix$ ${}$\"\n trade_action_{}_desc: \"$trade_action_trade_relic_desc$\""
    for line in lines:
        if line.startswith("#"):
            result = line
        elif line.strip():
            result = template_string.format(line, line, line)
        else:
            result = ""

        file.write(result + "\n")

print(f"Results have been written to {output_file}")
